apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: default
  namespace: openshift-ingress-operator
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true  
spec:
  routeAdmission:
    wildcardPolicy: WildcardsAllowed
  defaultCertificate:
    name: lets-encrypt-certs-tls

