apiVersion: org.eclipse.che/v2
kind: CheCluster
metadata:
  name: devspaces
  namespace: openshift-devspaces
spec:
  devEnvironments:
    containerBuildConfiguration:
      openShiftSecurityContextConstraint: container-build
    defaultEditor: che-incubator/che-code/insiders
    defaultNamespace:
      template: <username>-devspaces
    secondsOfInactivityBeforeIdling: -1
    secondsOfRunBeforeIdling: -1
    maxNumberOfWorkspacesPerUser: 5
    maxNumberOfRunningWorkspacesPerUser: 2
    storage:
      pvcStrategy: per-workspace
  components:
    cheServer:
      debug: false
      logLevel: INFO
    dashboard: {}
    database:
      credentialsSecretName: postgres-credentials
      externalDb: false
      postgresDb: dbche
      postgresHostName: postgres
      postgresPort: "5432"
      pvc:
        claimSize: 1Gi
    devWorkspace:
      runningLimit: '5'
    devfileRegistry: {}
    imagePuller:
      enable: true
      spec:
        images: >-
          universal-developer-image-ubi8-latest=quay.io/redhat_na_ssa/universal-developer-image@sha256:72b8edb995f76eb5575e7c3d01c787abed78023ea96d12c0ef54493971c7e299;universal-developer-image-ubi8-latest=quay.io/devfile/universal-developer-image@sha256:9777fcda747644a69c5422013a263413dd1268d55b04a5d5195f52ff881af107
    metrics:
      enable: true
    pluginRegistry: {}
  containerRegistry: {}
  networking:
    auth:
      gateway:
        configLabels:
          app: che
          component: che-gateway-config
