apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knative-components
  namespace: openshift-gitops
  labels:
    {{- include "argo-applications.labels" . | nindent 4 }} 
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "20"    
spec:
  project: default
  source:
    repoURL: {{ .Values.gitRepo.URL }}
    targetRevision: {{ .Values.gitRepo.targetRevision }}
    path: operators/openshift-serverless/knative-components
    directory:
      include: '*.yaml'
  destination:
    server: https://kubernetes.default.svc
    # namespace: openshift-serverless
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true    
    retry:
      limit: 5
      backoff:
        duration: 1m # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy