apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-pipelines-operator-rh
  namespace: openshift-operators
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: hyperfoil-bundle
  source: community-operators
  sourceNamespace: openshift-marketplace