kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: nexus-argo-route
  namespace: sonatype-nexus
spec:
  to:
    kind: Service
    name: nexusrepo-sonatype-nexus-service
    weight: 100
  port:
    targetPort: application
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
  wildcardPolicy: None